### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0

### ISSUE THREAD

**Issue by AmanChugh** [plattysoft/Leonids#35]
Getting IndexOutOfBoundsException on Click on of Button while using Vector images. :-

java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
                                                                                         at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                         at java.util.ArrayList.remove(ArrayList.java:403)
                                                                                         at com.plattysoft.leonids.ParticleSystem.activateParticle(ParticleSystem.java:518)
                                                                                         at com.plattysoft.leonids.ParticleSystem.oneShot(ParticleSystem.java:427)
                                                                                         at com.plattysoft.leonids.ParticleSystem.oneShot(ParticleSystem.java:411)
                                                                                         at com.example.amandeepsingh.demoexample.MainActivity.onClick(MainActivity.java:56)
                                                                                         at android.view.View.performClick(View.java:4785)
                                                                                         at android.view.View$PerformClick.run(View.java:19884)
                                                                                         at android.os.Handler.handleCallback(Handler.java:746)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)

**Comment by plattysoft** [comment]
Vector images are not supported in the current version, only Bitmap Drawables.

**Comment by plattysoft** [comment]
fixed in #57
